<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="testconf"
    nsURI="http://testconf/1.0" nsPrefix="testconf">
  <eAnnotations source="Kirjeldus"/>
  <eClassifiers xsi:type="ecore:EClass" name="system">
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" upperBound="-1" eType="#//node"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tester" upperBound="-1"
        eType="#//tester" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nimi" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testib" eType="#//tester"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="tester">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nimi" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sugu" eType="#//Sugu"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Testitav"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Sugu">
    <eLiterals name="Mees"/>
    <eLiterals name="Naine" value="1"/>
  </eClassifiers>
</ecore:EPackage>
